name: mqtt-piglow
version: 1.0
vendor: Xiaoguo, Liu <xiaoguo.liu@canonical.com>
summary: This is a MQTT demo app for snappy
description: Using MQTT protocol to contrl the Piglow light
icon: icon.png

services:
  mqtt-piglow:
    start: bin/mqtt-piglow
    caps:
     - network-client
     - network-service   

parts:
  mqtt:
    plugin: go
    source: ./src/mqtt-piglow
